kind: ConfigMap
apiVersion: v1
metadata:
  name: poststarthook
data:
  poststart.sh: |
    #!/bin/bash
    exec >logfile.txt 2>&1
    host=${HOSTNAME}
    echo "host: $host"
    number=${HOSTNAME//[!0-9]/}
    echo "NUMBER: $number"
    sleep 3
    if [ "$HOSTNAME" = "mongo-0" ]; then
      mongosh --eval "rs.initiate( { _id : 'rs0', members: [ { _id: 0, host: 'mongo-0.mongo.default.svc.cluster.local:27017', priority: 0.5 } ] })"
    else
      mongosh --host "rs0/mongo-0.mongo,mongo-1.mongo,mongo-2.mongo,mongo-3.mongo" --eval "rs.add( { _id: "$number", host: '"$host".mongo:27017', priority: 0.5, votes: 1} )"
    fi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  # This is a "headless" service.
  clusterIP: None
  selector:
    role: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 3
  selector:
    matchLabels:
      role: mongo
  template:
    metadata:
      labels:
        role: mongo
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - name: mongo
        image: mongo:6.0.2
        command:
          - mongod
        args:
          - "--replSet=rs0"
          - "--bind_ip=0.0.0.0"
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: storage
            mountPath: /data/db
          - name: hookvolume
            mountPath: /opt/poststart.sh
            subPath: poststart.sh
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", /opt/poststart.sh]
      volumes:
        - name: hookvolume
          configMap:
            name: poststarthook
            defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 256Mi