kind: ConfigMap
apiVersion: v1
metadata:
  name: poststarthook
data:
  poststart.sh: |
    #!/bin/bash
    exec >logfile.txt 2>&1
    host=${HOSTNAME}
    number=${HOSTNAME//[!0-9]/}
    sleep 3
    # The status code can help identify if the member is currently connected to the replicaset.
    rs_status_code=$(mongosh --quiet --eval 'rs.status()')
    if [[ $rs_status_code = "" ]]; then
      if [ "$HOSTNAME" = "mongo-0" ]; then
        # Initiates the replicaset.
        mongosh --eval "rs.initiate( { _id : 'mySet', members: [ { _id: 0, host: 'mongo-0.mongo.default.svc.cluster.local:27017', priority: 0.5 } ] })"
      else
        # Adds member to the replicaset.
        mongosh --host "mySet/mongo-0.mongo,mongo-1.mongo,mongo-2.mongo,mongo-3.mongo" --eval "rs.add( { _id: "$number", host: '"$host".mongo:27017', priority: 0.5, votes: 1} )"
      fi
    fi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  # This is a "Headless" Service.
  clusterIP: None
  selector:
    role: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 3
  selector:
    matchLabels:
      role: mongo
  template:
    metadata:
      labels:
        role: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:6.0.2
        command:
          - mongod
        args:
          - "--replSet=mySet"
          - "--bind_ip=0.0.0.0"
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: storage
            mountPath: /data/db
          - name: hookvolume
            mountPath: /opt/poststart.sh
            subPath: poststart.sh
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", /opt/poststart.sh]
      volumes:
        - name: hookvolume
          configMap:
            name: poststarthook
            defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 256Mi
