apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  # NodePort allows access from outside the cluster.
  type: NodePort
  selector:
    app: nginx
  ports:
      # Exposes the Kubernetes service within the cluster.
    - port: 80
      # Port which the service will send requests to.
      targetPort: 80
      # NodePort range: 30000-32767.
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: samuelwalters/nginx-image:v3
          ports:
            - containerPort: 80
          imagePullPolicy: Always