apiVersion: v1
kind: Service
metadata:
  name: user-app-service
spec:
  # This is the default type, but it is put here as a reminder.
  # Note: With type ClusterIP, you can only access this service inside the cluster.
  type: ClusterIP
  selector:
    app: user-app
  ports:
    - port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: samuelwalters/user-app:v5
          # Specifying the containerPort here is entirely informational.
          # This port is already exposed due to the service found above (user-app-service).
          ports:
            - containerPort: 3000
          imagePullPolicy: Always