apiVersion: v1
kind: Service
metadata:
  name: user-app
spec:
  selector:
    app: user-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: samuelwalters/user-app:v1
          ports:
            - containerPort: 3000
          imagePullPolicy: Always